### ISSUE TITLE
Enrollment failure

### ISSUE THREAD

**Issue by btry** [flyve-mdm/flyve-mdm-glpi-plugin#10]
@blanchouins said in #9 : 

>  Invitation don't include the download link of android application.
> 
> I downloaded application from Google Play, but I can't enroll my device. When app stated, asked me to enter my name, email, and to create certificate. All steps are OK, but when clicking to "Start Enrollment", application return me "fail" message

**Comment by btry** [comment]
Please enable debug mode in the settings of the plugin.

![image](https://cloud.githubusercontent.com/assets/14139801/21457218/c0d72a5e-c92d-11e6-87e1-dfc5d0dcb773.png)

Enrollment process contains many checks. With the debug mode enabled, the plugin will send an explicit message about the reason of the failure. The device will display it on its screen.

**Comment by btry** [comment]
Also check #11 I opened for you about the missing URL.  It may impact enrollment too.

**Comment by blanchouins** [comment]
I activate the debug mode in the plugin but I have no more detail on my device



On Fri, Dec 23, 2016 at 5:12 PM +0100, "btry" <notifications@github.com<mailto:notifications@github.com>> wrote:


Also check #11<https://github.com/flyve-mdm/flyve-mdm-glpi/issues/11> I opened for you about the missing URL. It may impact enrollment too.

**Comment by blanchouins** [comment]
I activate the debug mode in the plugin but I have no more detail on my device

![screenshot_2017-01-02-09-21-06](https://cloud.githubusercontent.com/assets/24428557/21586151/aa1d75b4-d0cd-11e6-90e0-c094becabea9.png)

**Comment by btry** [comment]
Hi

Please be careful when publishing screenshots : there is your serial number here.

If the message is still not explicit then the failure is in the very begining of the enrollment process.

Let's check the data in the QR code : 
use the android application **barcode scanner**  or similar to flash the QR code. show here the data contained in the QR code, and revealed by the application. You should get something similar to the following JSON : 

```
{"url":"https://domain.com/apirest.php", "user_token":"azertyuiop","invitation_token":"qsdfghjklm"}
```

Do **NOT** publish here the content of user_token or invitation_token. These are passwords.

**Comment by blanchouins** [comment]
Ok thank you, I see the problem, my URL is not open on Internet. I will resolve that

**Comment by btry** [comment]
If your local network has a Wifi hostspot, then you can connect your device this way and enroll without exposing your setup on internet.

**Comment by btry** [comment]
The agent use HTTP(S) to enroll. After a succcessful enrollment all communication use with MQTT protocol (needs a Mosquitto server / broker)

**Comment by btry** [comment]
No feedback; closing.
