### ISSUE TITLE
Create project page

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-glpi-plugin#100]
Create gh-pages as requested in this issue: flyve-mdm/flyve-mdm.github.io#13

**Comment by ajsb85** [comment]
Hi, @btry 

Here is the project site: http://flyve.org/flyve-mdm-glpi-plugin/
We need to improve it later.

Thanks @Gianfranco97

**Comment by btry** [comment]
We may ad a link to this page in the readme

**Comment by ajsb85** [comment]
@btry Yes, I will try to improve the patch of the URLs and change to HTTPS before publish it.

**Comment by AnaelMobilia** [comment]
@ajsb85 For information, the website is down :)

**Comment by Gianfranco97** [comment]
@AnaelMobilia  

All set friend, the page is working now, you can visit it through the following link: http://flyve.org/glpi-plugin/

Thanks for the info.
