### ISSUE TITLE
Code documentation

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-glpi-plugin#103]
Hi, @Naylin15 

We are using `phpDocumentor` and `PHPDocumentor MarkDown export` to generate the documentation.

Your task is complete all documentation inside the code.

- [x] Create a branch (git-flow branching model)
- [x] Write standardized commit messages (Conventional Commits)
- [x] Generate a Pull Request. (Add label: documentation)

@btry will write to you the steps to generate the documentation.

Good luck.

Btw, the objective of this task is to understand in deep how the code works.

**Comment by btry** [comment]
The project requires **consolidation/robo**. This is a tool to automate tasks 

It relies on RoboFile.php in the root of the project. This file contains a task to automate the documentation generation.

Assuming you ran composer install just chdir to the plugin and un the following

```shell
vendor/bin/robo documentation:build
```
It calls the method documentationBuild in RoboFile.php and generates documentation in the subfolder *doc**.

In the wiki repo of the project there is a folder devdoc/code/ the generated .md files must overwrite the content of this folder.

**Comment by ajsb85** [comment]
Good job @Naylin15 

Could you generate the markdown files and update the files on the Wiki using git?

- [ ] Generate markdown files of the documentation
- [ ] Update the Wiki of the project using git

This is the link to clone the wiki of this repository:
https://github.com/flyve-mdm/flyve-mdm-glpi-plugin.wiki.git

Thanks.

**Comment by ajsb85** [comment]
Issue close h
