### ISSUE TITLE
Invitation don't include the download link of android application

### ISSUE THREAD

**Issue by btry** [flyve-mdm/flyve-mdm-glpi-plugin#11]
@blanchouins said in #9 : 

>  Invitation don't include the download link of android application.

I don't reproduce this.

In the web interface check the settings of your account 

![image](https://cloud.githubusercontent.com/assets/14139801/21457822/4cf71ebe-c932-11e6-91e3-a26442481429.png)

Maybe you receive an error message like this 
![image](https://cloud.githubusercontent.com/assets/14139801/21457954/3863da18-c933-11e6-97b6-835852c6027d.png)

If yes, then you probably changed something related to the entities in GLPi and lost access to some data specific to Flyve MDM.

**Comment by blanchouins** [comment]
No error message, but Download URL paramater is empty

[cid:image001.png@01D264D8.71D78930]



De : btry [mailto:notifications@github.com]
Envoyé : vendredi 23 décembre 2016 17:10
À : flyve-mdm/flyve-mdm-glpi
Cc : BLANCHOUIN Sylvain; Mention
Objet : [flyve-mdm/flyve-mdm-glpi] Invitation don't include the download link of android application (#11)


@blanchouins<https://github.com/blanchouins> said in #9<https://github.com/flyve-mdm/flyve-mdm-glpi/issues/9> :

Invitation don't include the download link of android application.

I don't reproduce this.

In the web interface check the settings of your account

[image]<https://cloud.githubusercontent.com/assets/14139801/21457822/4cf71ebe-c932-11e6-91e3-a26442481429.png>

Maybe you receive an error message like this
[image]<https://cloud.githubusercontent.com/assets/14139801/21457838/63ebdb96-c932-11e6-922e-bb88f8810d1c.png>

If yes, then you probably changed something related to the entities in GLPi and lost access to some data specific to Flyve MDM.

**Comment by blanchouins** [comment]
No error message, but Download URL paramater is empty

![image](https://cloud.githubusercontent.com/assets/24428557/21586132/6b705872-d0cd-11e6-9e44-0827bae46361.png)

**Comment by btry** [comment]
When you self created your account you created a new entity for your account. Its name is the email of your account. 

Get the ID of this entity,
Open the table  glpi_plugin_storkmdm_entityconfigs in your DBMS

It must contain a row having the same ID as your entity. It contains a column for the download URL of the Flyve MDM agent for Android. 

You should see the value without editing it (grayed under the label, as below): 
![image](https://cloud.githubusercontent.com/assets/14139801/21586666/afa89a8a-d0d3-11e6-81a6-8212f7758357.png)

**Comment by btry** [comment]
Related to this issue : the default download URL was not up to date in the backend. 

Updated in  this commit  c746a9fea35ad33cd1c00cfe2cd7eaa3fdda2231 to use official source.

**Comment by btry** [comment]
Seems the problem is more a web app problem than a backend problem. While playing with the frontend, I can finally show the URL.

**Comment by btry** [comment]
The issue may be related to performance of the API when loading many data after login. 

We will attempt to make more aggressive parallelization of HTTP request and optimize some of them to reduce load in the backend.

**Comment by btry** [comment]
An other thing to do : add more indexes in the schema

**Comment by ajsb85** [comment]
The issue is in the Dashboard, I will fill an issue in that repository.
