### ISSUE TITLE
Refactor package upload code

### ISSUE THREAD

**Issue by btry** [flyve-mdm/flyve-mdm-glpi-plugin#126]
In GLPI exists a function isAPI (autoload.function.php)

It is way better to use it to improve prepareInputForAdd() and prepareInputForUpdate() in PluginFlyvemdmPackage to detect if the creation or update of a package is done from the API or the UI.

By the way, these methods need refactor, there are issues. Can be fixed at the same time

**Comment by DIOHz0r** [comment]
Changes merged
