### ISSUE TITLE
Trying to make it enroll

### ISSUE THREAD

**Issue by grego1981** [flyve-mdm/flyve-mdm-glpi-plugin#129]
### Expected behaviour
Enroll device to server
### Actual behaviour
Android application crashes
### Environment Details

- HTTP server version: Apache/2.4.18 (Ubuntu) Server 
- GLPi version: 9.2
- Flyve MDM version: 2.0.0-dev
- FusionInventory version: 9.2+1.0
- Mosquitto version:  1.4.8 (build date Mon, 26 Jun 2017 09:31:02 +0100)
- Mosquitto's auth plugin  version: (0.0.7-2build1)

### Steps to reproduce the behaviour

1.Enroll device via QR with correct url and set up deep link on my server.
2.App crashes, no error on server
3.When trying to enroll from URL on phone I get to the link and when I hit enroll button I get object not found in play store.

### Screenshots, backtraces or logs

Please check your logs for passwords, device serial numbers, IP addresses or any sensitive content

php-errors.log
no error concerning flyvemdm

sql-errors.log
no error

HTTP server error log
no error

**Comment by btry** [comment]
hi

@grego1981 Can you tell the version of the Android agent you're using ?

**Comment by ajsb85** [comment]
Hi, @grego1981 

You are right  @btry 

Join us to the testing program.
https://play.google.com/apps/testing/org.flyve.mdm.agent

Send me your email address to added you.
Thanks.

**Comment by grego1981** [comment]
Hi all! I'm using the latest version from the play store 0.99.46
I'm sending you my email 

Thank you!

**Comment by ajsb85** [comment]
@grego1981 I got it, I already added you as license testing.

Check if you can join to the testing program please.

Thanks

**Comment by grego1981** [comment]
I can login but Google says the app is not available in my country (Greece).

**Comment by ajsb85** [comment]
Hi, @grego1981

I published the agent for new users on Google Play.
Could you try again?
And check if the user logged is the same of your email provided.

Regards.

**Comment by grego1981** [comment]
This time the app is available for installation! Thank you! I will try and give you my feedback.
Gregory

**Comment by ajsb85** [comment]
Every project has a website for with a better documentation.
