### ISSUE TITLE
Handle missing icon

### ISSUE THREAD

**Issue by btry** [flyve-mdm/flyve-mdm-glpi-plugin#136]
Now packages are parsed a few minutes later, the form needs to handle missing icon.
This is not very nice.

![image](https://user-images.githubusercontent.com/14139801/31337976-de28edb8-acfd-11e7-8a80-b2c9f3ade448.png)

We need to replace the icon by a "no icon" picture or not show any pic at all. 

Update of the package.tml file needed, along with the showForm() logic

**Comment by ajsb85** [comment]
Hi,  @btry 
Try to write a short tittle and describe more in the body of the issue.
👍

**Comment by btry** [comment]
fix merged
