### ISSUE TITLE
Change the URL of the lostPassword email template

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-glpi-plugin#139]
Hi, @DIOHz0r 

We need to extend the endpoint lostPassword
To add own URL for the Flyve MDM layout

Thanks

**Comment by ajsb85** [comment]
We need to extend this endpoint of the GLPI core to use custom URL for the front-end.
Maybe, we can use the referrer URL as argument for the POST request.

![image](https://user-images.githubusercontent.com/663460/32059547-c39ecb8a-ba6c-11e7-8df2-8724abf1caec.png)

Use case (Flyve MDM ):

>  Custom Forget Password page (Style of Flyve MDM)
> The user got the link to reset the password
> Custom Reset Password page (Style of Flyve MDM)

Actual URL of the GLPI core to request a password reset, is easy to change with the API REST
https://dev.flyve.org/glpi/front/lostpassword.php?lostpassword=1

But the link to edit the password is the same UI of GLPI.

Maybe, we can add a custom key with the callback URL for the reset page UI.

Thanks

**Comment by btry** [comment]
This is a customization of  the content of the notification, no code needed for that.

Is the update of the dev server satisfying ? Can we close ?

**Comment by ajsb85** [comment]
Hi, @Naylin15 

Write with @btry an article in the wiki about "customization of the content of the notification"

Thanks.
