### ISSUE TITLE
Fatal error on attempt to install 2.0 on GLPI < 9.2

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-glpi-plugin#145]
Hi, @btry 

Could you handle better this error?

![image](https://user-images.githubusercontent.com/663460/32012520-6749303c-b9b8-11e7-951a-c5499dc6ecfe.png)

GLPI 9.1.6
FusionInventory 9.1+1.0

**Comment by btry** [comment]
We need to re-add the deprecated version check system, and see if in GLPI core something can be done to prevent such case. Someday we will need to remove retro-compatibility code.
