### ISSUE TITLE
Wrong time of last contact?

### ISSUE THREAD

**Issue by grego1981** [flyve-mdm/flyve-mdm-glpi-plugin#162]
### Expected behaviour
Show time of last contact in local time of phone or system
### Actual behaviour
Shows the GMT time not the GMT+2:00 which is that of the phone and server.
### Environment Details

- GLPi version: 9.2
- Flyve MDM version: 2.0.0 built today 15:00

**Comment by DIOHz0r** [comment]
The plugin is using UTC by default, this was changed to use GLPI's timezone now (PR #163).
