### ISSUE TITLE
Agent username not unique

### ISSUE THREAD

**Issue by DIOHz0r** [flyve-mdm/flyve-mdm-glpi-plugin#177]
### Expected behaviour
The GLPI user account of the agent registered must be unique

### Actual behaviour
When a new agent is trying to do the enroll process a user account is created using the serial number of the device, if  the username is already registered the agent fails to do the enrollment.

### Environment Details

- GLPi version: 9.2
- Flyve MDM version: 1.0
- FusionInventory version:  9.2
- Mosquitto version: 3.1
- Mosquitto's auth plugin  version: 0.1.2

### Steps to reproduce the behaviour

You have multiple ways to do this: 
Case 1:
1. Create one User in GLPI using the device serial
2. Try to enroll the device.

Case 2:
1. Enroll The device
2. Delete & purge the computer and the agent at GLPI leaving the User created, all this without the device connected
3. Try to enroll again the device.

Case 3 (most dificult but almost like case 1):
1. Enroll a device 
2. Try to enroll other device with the same serial.

### Screenshots, backtraces or logs

![imagen](https://user-images.githubusercontent.com/1426313/32779613-cc6f4ad0-c914-11e7-8d93-fe3cf0c1b4a1.png)

**Comment by btry** [comment]
Hi

before fixinig this,  we must ask ourselves if this issue should be fixed in GLPI instead of the plugin.

**Comment by btry** [comment]
In GLPI, having 2 users with the same name (aka login) is forbidden, so we need to add a check in the enrollment procedure

**Comment by btry** [comment]
Let's create a private method in PluginFormcreatorAgent to check if the user already exists. This method will b e called in several enrollment scenarios (enrolment with service discovery (DHCP + DNS))

**Comment by btry** [comment]
We need to consider solving #172 first as it will help to no longer rely on serial unicity, thus choose an alternate user name for the agent account.

**Comment by DIOHz0r** [comment]
Hi, there wouln't be necesary to check if the username exist before the enroll process with the new fix from the PR.
