### ISSUE TITLE
All keys of the Get Item Type Agent in the Search Option List

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-glpi-plugin#179]
Hi, @btry 

Could you add the same data of the item type PluginFlyvemdmAgent in the listSearchOption endpoint?

Thanks.

**Comment by ajsb85** [comment]
An example:

Compare the data of the same ID 1

```JSON
    {
      "PluginFlyvemdmAgent.name": "tbugier@teclib.com",
      "PluginFlyvemdmAgent.id": 1,
      "PluginFlyvemdmAgent.PluginFlyvemdmFleet.name": "not managed fleet",
      "PluginFlyvemdmAgent.Computer.id": 1,
      "PluginFlyvemdmAgent.Computer.serial": "BH91BQDY16__",
      "PluginFlyvemdmAgent.Computer.User.id": 8,
      "PluginFlyvemdmAgent.PluginFlyvemdmFleet.id": 1,
      "PluginFlyvemdmAgent.last_contact": null,
      "PluginFlyvemdmAgent.Computer.User.realname": "bugier",
      "PluginFlyvemdmAgent.version": "0.99.46",
      "PluginFlyvemdmAgent.is_online": 0
    },
```

```JSON
  {
    "id": 1,
    "name": "tbugier@teclib.com",
    "version": "0.99.46",
    "computers_id": 1,
    "users_id": 0,
    "wipe": 0,
    "lock": 0,
    "enroll_status": "enrolled",
    "entities_id": 0,
    "plugin_flyvemdm_fleets_id": 1,
    "last_report": null,
    "last_contact": null,
    "is_online": 0,
    "certificate": "",
    "mdm_type": "android",
    "has_system_permission": 0,
    "links": [
      {
        "rel": "Computer",
        "href": "https://dev.flyve.org/glpi/apirest.php/Computer/1"
      },
      {
        "rel": "Entity",
        "href": "https://dev.flyve.org/glpi/apirest.php/Entity/0"
      },
      {
        "rel": "PluginFlyvemdmFleet",
        "href": "https://dev.flyve.org/glpi/apirest.php/PluginFlyvemdmFleet/1"
      }
    ]
  },
```

**Comment by ajsb85** [comment]
I can get the mdm type by the getItem but no with force display of the search endpoint.
And in the list of the search option does not exist this field

**Comment by btry** [comment]
OK, I got it. 

Both problems are related. By adding a search option in the class, the column is available for display with forcedisplay, and of course, the search option will appear in the list search options endpoint.

**Comment by ajsb85** [comment]
@btry We need in the search option list:
First Name (User)
MDM Type (Agent)

**Comment by btry** [comment]
MDM type is added in  the PR I just created. 

About the user name: this may be the human owninig the device or the user account for the agent. In both cases a search option exists to get it from this itemtype. However you cannot get it when GETting PluginFlyvemdmAgent.

GET verb retrieves data from a single table, without any JOIN operation. Use the Search endpoint. It is designed to do join operations for you.

**Comment by ajsb85** [comment]
@btry Actually I can get  PluginFlyvemdmAgent.Computer.User.realname
