### ISSUE TITLE
Build UI for GLPI

### ISSUE THREAD

**Issue by btry** [flyve-mdm/flyve-mdm-glpi-plugin#20]
GLPI is a inventory and helpdesk tool first, and Flyve MDM provides its own UI for a standalone usage.

For those who use GLPI the "regular" way, we need to provide a user interface to allow devices management from a unique place.

**Comment by btry** [comment]
done (many commits).

**Comment by ajsb85** [comment]
You can add the reference in the PR to close automatically 👍
