### ISSUE TITLE
Add openstreetmap to show geolocations

### ISSUE THREAD

**Issue by btry** [flyve-mdm/flyve-mdm-glpi-plugin#25]
Hi, @ajsb85

The feature is added but needs some cosmetic and UX improvements.

Thanks

**Comment by ajsb85** [comment]
Hi, @btry 

OpenStreetMap is already in the Web Dashboard of Flyve MDM, this issue is for the GLPI UI?

Regards.

**Comment by btry** [comment]
Hi

Yes, this is for the GLPI UI (that's why it is in this repo). The feature is done, but needs some cosmetic and UX improvements.

**Comment by DIOHz0r** [comment]
Hello, Could this issue be closed and then create another for the UX improvements?

**Comment by ajsb85** [comment]
@DIOHz0r You can create new one. 
And reference both in the PR.
