### ISSUE TITLE
Install Script and Docker Images

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-glpi-plugin#38]
The user can deploy their instance of all components without third-party access to data or information. And the network connection is over Transport Layer Security by default.
Warning message when TLS is not enable.

**Comment by btry** [comment]
The plugin shall show a warning in the homepage of GLPI
the web UI should also show a warning if TLS is not used.

**Comment by ajsb85** [comment]
I will move this issue to the docker repository.
