### ISSUE TITLE
Document how to setup the backend

### ISSUE THREAD

**Issue by btry** [flyve-mdm/flyve-mdm-glpi-plugin#4]
README.md does not contains enough info.

The manual installation procedure is rather long, the it might be a good idea to create INSTALL.md

Suggestions ?

**Comment by ajsb85** [comment]
Let's use Read the Docs

https://readthedocs.org/

**Comment by ajsb85** [comment]
Create the wiki pages for these topics:

* Home
* How to install
* How to use
* How it works
* How to build
* Code documentation

https://github.com/flyve-mdm/flyve-mdm-glpi/wiki

Note: The code documentation can be generated in markdown from the comments of the code.
(Example: Javadoc to Markdown)

**Comment by ajsb85** [comment]
@btry Could you update this task for partner priority?

**Comment by btry** [comment]
Installation documentation in the wiki
