### ISSUE TITLE
Plugin Version Matrix

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-glpi-plugin#48]
Create a table with the supported list for the `README.md`:

Eg:

:x: - incompatible 

|GLPI|9.1.1|9.1.2|9.1.3|9.2.0|
|:----|----|----|----|---|
|Flyve MDM|1.x.x|1.x.x|1.x.x|2.0.0-dev|
|FusionInventory|9.1-1.1|9.1-1.1|9.1-1.1|master branch|

**Comment by btry** [comment]
added in the wiki 

https://github.com/flyve-mdm/flyve-mdm-glpi-plugin/wiki/Installation
