### ISSUE TITLE
Add agent phone number

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-glpi-plugin#53]
Add phone number key in the properties of the Agent.

**Comment by btry** [comment]
I agree this data is useful, but not in this itemtype. 

There is a plugin for simcards. It can save the phone number; I think it is better

**Comment by ajsb85** [comment]
@btry Yes, perfect. 

+1

**Comment by btry** [comment]
related to #57

**Comment by ajsb85** [comment]
Hi, @btry

The glpi-project/glpi#2311 is merged.
I will close this issue.

We need the feature to edit the inventory in the Web Dashboard.
