### ISSUE TITLE
Multi entity management 

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-glpi-plugin#56]
Must be identifiable in the solution

**Comment by btry** [comment]
Already implemented; available in the GLPI's UI. Now we need to see in real world if I defines all use cases correctly.

**Comment by ajsb85** [comment]
Hi, @btry 

So, I need to move this issue to the dashboard?

**Comment by btry** [comment]
Yes, move this issue, and we will open bugs if the plugion has mis behavior with multi entity. it is designed to be multi entity capable.
