### ISSUE TITLE
SemVer Regex to validate agent version topic in MQTT

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-glpi-plugin#59]
http://semver.org/#spec-item-9

`/\bv?(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[\da-z\-]+(?:\.[\da-z\-]+)*)?(?:\+[\da-z\-]+(?:\.[\da-z\-]+)*)?\b/ig;`

**Comment by btry** [comment]
done in commit 345b4822766047fd82c753fb318df14993114a63
