### ISSUE TITLE
Review enrollment process

### ISSUE THREAD

**Issue by btry** [flyve-mdm/flyve-mdm-glpi-plugin#60]
**Review enrollment process - provide a regular user account per device**

Currently devices have a token to authenticate as the user account of their owner.

users can bave a category.

The plugin should create a **Flyvemdm Agent** user category and create an account per device with this category (during enrollment).

The device needs to retain its api token and negociate a periodic renew with the backend.

**Comment by ajsb85** [comment]
Hi, this issue is closed then?

@btry moved from Tasks in progress to Merged into develop branch in Backend on 5 Jul
