### ISSUE TITLE
Provide helpdesk information to agents and invitation email

### ISSUE THREAD

**Issue by btry** [flyve-mdm/flyve-mdm-glpi-plugin#61]
We want to compelte the inviattion email with support information (company email, phone number) of the entity owning the device to enroll.

We also want the device show these information on screen.

To complete this, let's create a tag in GLPI to store missing informations and provide them from the API.

Check data available in entity, and check if recursion to upper entity is possible.

**Comment by ajsb85** [comment]
Hi, @btry 

I think its already added in the dev version.

Can I close this issue?
