### ISSUE TITLE
Create a turnkey downlaodable VM of the whole solution for testers

### ISSUE THREAD

**Issue by btry** [flyve-mdm/flyve-mdm-glpi-plugin#62]
We need a VM containing
- GLPI
- Flyve MDM Plugin
- Mosquitto
- Web dashboard

all as a pre-configured enviroment, for testing purpose. 

Let's do it simple to begin, and provide the virtual appliance downloadable.

**Comment by ajsb85** [comment]
Issue moved to https://github.com/flyve-mdm/flyve-mdm-docker/issues/4
