### ISSUE TITLE
Create a new button for lock the device on Dashboard

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/flyve-mdm-glpi-plugin#67]
The android agent has the possibility to lock the screen but in dashboard does not exist a way to lock the screen, this is the proposal of the message to send by MQTT

```
{
    "lock": [
        { "locknow" : "true|false"}
    ]
}
```

**Comment by btry** [comment]
Hi

The feature is already implemented in the backend and its own user interface. The MQTT message body is 

```json
{
    "lock": "now"
}
```

and is sent on to the device's topic **/Command/Lock**
