### ISSUE TITLE
Add captcha feature

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-glpi-plugin#69]
### Add captcha feature to be used on the following screens: 

- https://github.com/flyve-mdm/flyve-mdm-web-dashboard/issues/74

![](https://user-images.githubusercontent.com/19965590/28285943-88b5b720-6b04-11e7-8c48-140f4bfe1767.png)

- https://github.com/flyve-mdm/flyve-mdm-web-dashboard/issues/76

![localhost-3000-createaccount](https://user-images.githubusercontent.com/19965590/28286901-be1f4ab8-6b07-11e7-84e0-9f1d9283719a.png)

**Comment by btry** [comment]
GLPI does not offers much for the features we need. Here is a proposal we can discuss to improve it.

- it sends a POST request to an endpoint in charge of generating a captcha. The captcha has a limited lifetime of a few seconds or minutes. The answer contains the captcha to solve and a random string identiffying it.
- The human or bot challenges the captcha and fils your form.
- the dashboard sends the account creation or recovery request (they are either PUT or POST HTTP verbs) with the solution of the captcha and its random string ID.
- the backend finds the captcha based on the random string and evaluates the answered text.
- if it suceeds the request continues, if not, it is cancelled.

**Comment by ajsb85** [comment]
I like it, but we need to refresh the captcha after this lifetime.

**Comment by btry** [comment]
Indeed. The dashboard can refresh the captcha when the lifetime is close to its end. 80% ? 90% ?

The lifetime should be hardcoded for now in both sides, don't go too far in complexity.

**Comment by btry** [comment]
there are 2 widely used packages for PHP. One is for Laravel and seems require the Laravel framework. This is a no go for me.

The other is lighter and renders rather nicely: https://github.com/Gregwar/Captcha

**Comment by btry** [comment]
Hi @Gianfranco97 

The captcha feature is implemented. See documentation

https://github.com/flyve-mdm/flyve-mdm-glpi-demo/wiki/Self_create_an_user_account

**Comment by btry** [comment]
Also, there is no captcha for password recovery yet. I contributed to GLPI to allow password recovery from the API, but I did not implemented a captcha feature because it does not exists in the regular UI.

**Comment by btry** [comment]
done
