### ISSUE TITLE
Add a boolean field for newsletter

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-glpi-plugin#70]
### Add a boolean field in the user's profile to subscribe to a newsletter. 
This will be necessary when creating a new user

- https://github.com/flyve-mdm/flyve-mdm-web-dashboard/issues/76

![localhost-3000-createaccount](https://user-images.githubusercontent.com/19965590/28287318-357dd8a8-6b09-11e7-9be4-7e3009332a87.png)

**Comment by btry** [comment]
Done, documented here 

https://github.com/flyve-mdm/flyve-mdm-glpi-demo/wiki/Self_create_an_user_account
