### ISSUE TITLE
Validation token life

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-glpi-plugin#71]
### I need a way to know how much long time life have the validation token used in these screen:

- https://github.com/flyve-mdm/flyve-mdm-web-dashboard/issues/68

![localhost-3000-validateuser 3](https://user-images.githubusercontent.com/19965590/28291437-81d37942-6b18-11e7-8f8d-366f1832759a.png)

**Comment by btry** [comment]
The activation delay is hard coded to 1 day. 

If we don't allow customization then we can hard code it on both sides.

**Comment by ajsb85** [comment]
Then keep static the information about the 1 day at the moment.
