### ISSUE TITLE
opt-out mechanisms

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-glpi-plugin#72]
### Integration of opt-out mechanisms is needed

- https://github.com/flyve-mdm/flyve-mdm-web-dashboard/issues/72

![](https://user-images.githubusercontent.com/19965590/28167192-be009cec-67a8-11e7-9ff7-4a9f87203d1a.png)

**Comment by btry** [comment]
A registered user can delete an invitation. Is it not sufficielt to siply delete it ?

**Comment by ajsb85** [comment]
The guest user can not delete their invitation?

**Comment by btry** [comment]
No and this is wanted. This is an administrator's choice.

If the guest does not wants to answer the invitation he just needs to let the invitation expire itself.
