### ISSUE TITLE
change email user

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-glpi-plugin#73]
### Create a way to change the email to a user who just registered

- https://github.com/flyve-mdm/flyve-mdm-web-dashboard/issues/67

![](https://user-images.githubusercontent.com/19965590/28325605-3f22ea08-6bac-11e7-838b-cc4a7547a97e.png)

**Comment by btry** [comment]
Hi

get the ID of the current user
GET getFullSession

in the retuirned JSON get the key **glpiID**

Get all email addresses of the user.
GET User/:id/UserEmail
200 OK
```json
[
    {
        "id": 2,
        "users_id": 2,
        "is_default": 1,
        "is_dynamic": 0,
        "email": "a@a.com"
    },
    {
        "id": 3,
        "users_id": 2,
        "is_default": 0,
        "is_dynamic": 0,
        "email": "b@a.com"
    }
]
```

find the email address with is_default == 1

PUT UserEmail/:id
{"input": {"email": "newaddress@domain.com"}}

**Comment by ajsb85** [comment]
Very good.
