### ISSUE TITLE
Sign up option is available and the contact information

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-glpi-plugin#74]
### I need a way to know if the sign up option is available and the contact information 

- https://github.com/flyve-mdm/flyve-mdm-web-dashboard/issues/75
![](https://user-images.githubusercontent.com/663460/28144336-3ab041a4-676b-11e7-8709-c9657cb109e3.png)

![](https://user-images.githubusercontent.com/663460/27856655-062a884c-616f-11e7-8e99-f3fee5c6cb50.png)

**Comment by btry** [comment]
The demo plugin creates the service account you use to sign up.
- If the service user does not exists then the demo plugin is not installed
- if the service account exists but is disabled then the demo plugin is installed but fully disabled
  - either the plugin itself is disabled
  - either the plugin is configured to not allow account self creation

In all cases attempting to login with the service account will fail. 

You might try to login with the service account early and if it succeeds, show the signup features. If it fails, hide them.
