### ISSUE TITLE
New key for the Agent endpoint to know the MDM platform

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-glpi-plugin#77]
We need to add an icon in the device list for every MDM platform, Apple, Android (AOSP), Samsung, Uhuru Mobile, BlackBerry, Windows 10 Mobile.

**Comment by btry** [comment]
property added with this commit: 0036cb5ae817190c5227569401dd05776de0205b

Haldnes android and apple MDM types currently.

Will grow to other types after implementing abstraction layer between the backend and communication protocols (MQTT, Apple MDM, ...)
