### ISSUE TITLE
Super admin should be allowed to update invitations 

### ISSUE THREAD

**Issue by btry** [flyve-mdm/flyve-mdm-glpi-plugin#84]
Registered users can, so why not super admin ?

**Comment by ajsb85** [comment]
Hi, @btry  
 
Could we assign this issue to @DIOHz0r?

Thanks.

**Comment by DIOHz0r** [comment]
Hi @btry,

I'm not clear if you mean to this option from the image taken at dev flyve glpi.

![imagen](https://user-images.githubusercontent.com/1426313/32412476-59679aca-c1cf-11e7-9bb7-c19227ca9716.png)
(the registered user doesn't have any option to edit)

I found than the super admin doesn't show the action update. It that the issue?.

**Comment by btry** [comment]
I mean the permission to update an invitation. 

Here are the permissions of a registered user (flyve mdm demo plugin)
![image](https://user-images.githubusercontent.com/14139801/32435272-bf4ac9a4-c2e0-11e7-8a90-db6beead5bce.png)

and the permissions of  the super admin (flyve mdm plugin)
![image](https://user-images.githubusercontent.com/14139801/32435306-d7b92e5e-c2e0-11e7-8a0a-9175db969c37.png)

This is a matter of changing permissions in the installer, method createFirlstAccess()
(the method updates the profile of the user who installs the plugin, the user is commonly **glpi**)

We also need to add this permission on upgrade. Inspire from createFirstAccess() method to add rioghts in update_dev.php.
