### ISSUE TITLE
Harmonize datetime zone between plugin and GLPI

### ISSUE THREAD

**Issue by btry** [flyve-mdm/flyve-mdm-glpi-plugin#92]
GLPI is designed to use the timezone set in php.ini. 

The plugin sets its dates to UTC timezone.

The plugin should use the same timezone as GLPI.

**Comment by ajsb85** [comment]
Hi, @btry 

Could we assing it to @DIOHz0r ?

**Comment by btry** [comment]
yes !

**Comment by ajsb85** [comment]
@btry
