### ISSUE TITLE
Create a help center with the knowledge base provided by GLPI

### ISSUE THREAD

**Issue by btry** [flyve-mdm/flyve-mdm-glpi-plugin#93]
Use knowledge base to store articles for the help center and consume them with the API

**Comment by btry** [comment]
Unfortunately, the KB in GLPI does not works with the API

2 search options in KnowbaseItem are related to entities, but the table does not contains entities_d and is_recursive columns. The search engine builds a failing query.

Moreover the KnowbaseItem is linked to 4 relations (user, entitiy, group, profile) through 4 tables making complex to request items with these visibility constraints.

A redesign of the KB is needed. To be planned for GLPI 9.3.

**Comment by ajsb85** [comment]
Issue moved to: flyve-mdm/flyve-mdm-graphql-service#3
