### ISSUE TITLE
Enhance GLPI's API to allow access to anonymous FAQ entries

### ISSUE THREAD

**Issue by btry** [flyve-mdm/flyve-mdm-glpi-plugin#94]
Probably too late for GLPI 9.2, so let's plan for GLPI 9.3

**Comment by ajsb85** [comment]
Issue moved to:
https://github.com/flyve-mdm/flyve-mdm-graphql-service

**Comment by ajsb85** [comment]
Closed becasue, for security reasons GLPI does not allow anonymous endpoints
